# Generated by Django 3.2.9 on 2021-12-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211225_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
