# Generated by Django 3.2.9 on 2022-01-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
