# Generated by Django 3.2.9 on 2021-12-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('Perfume', 'Perfume'), ('Makeup', 'Makeup'), ('Body Care', 'Body Care'), ('Hair Care', 'Hair Care')], max_length=50, null=True)),
                ('sub_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Oriental', 'Oriental'), ('Foundation', 'Foundation'), ('Mascara', 'Mascara'), ('Eye Shadow', 'Eye Shadow'), ('Highlighter', 'Highlighter'), ('Bronzer', 'Bronzer'), ('Lip Gloss', 'Lip Gloss'), ('Rouge', 'Rouge'), ('Makeup Remover', 'Makeup Remover'), ('Kohl', 'Kohl'), ('Cream', 'Cream'), ('Body Lotion', 'Body Lotion'), ('Body Mist', 'Body Mist'), ('Shampo', 'Shampo'), ('Serums', 'Serums'), ('Conditioner', 'Conditioner'), ('Conditioner Cream', 'Conditioner Cream'), ('Protein And Creatine', 'Protein And Creatine'), ('Oils', 'Oils')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reviews_number', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
