# Generated by Django 3.2.9 on 2021-12-24 11:07

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211221_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to=product.models.saveCatImg),
            preserve_default=False,
        ),
    ]
