# Generated by Django 3.2.9 on 2021-12-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
