# Generated by Django 3.2.9 on 2021-12-31 19:02

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20211230_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='img',
            field=models.ImageField(default='', upload_to=product.models.saveOfferImg),
            preserve_default=False,
        ),
    ]
