# Generated by Django 3.2.9 on 2021-12-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reviews',
            new_name='reviews_number',
        ),
    ]
