# Generated by Django 3.2.9 on 2021-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211218_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='telephone_number',
        ),
    ]
