# Generated by Django 3.2.9 on 2021-12-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_jov_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cat1', 'CATEGORY1'), ('cat2', 'CATEGORY2'), ('cat3', 'CATEGORY3'), ('cat4', 'CATEGORY4'), ('cat5', 'CATEGORY5')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('tag1', 'TAG1'), ('tag2', 'TAG2'), ('tag3', 'TAG3'), ('tag4', 'TAG4'), ('tag5', 'TAG5')], max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
