# Generated by Django 3.2.9 on 2021-12-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211218_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Perfume', 'Perfume'), ('Makeup', 'Makeup'), ('Body Care', 'Body Care'), ('Hair Care', 'Hair Care')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Oriental', 'Oriental'), ('Foundation', 'Foundation'), ('Mascara', 'Mascara'), ('Eye Shadow', 'Eye Shadow'), ('Highlighter', 'Highlighter'), ('Bronzer', 'Bronzer'), ('Lip Gloss', 'Lip Gloss'), ('Rouge', 'Rouge'), ('Makeup Remover', 'Makeup Remover'), ('Kohl', 'Kohl'), ('Cream', 'Cream'), ('Body Lotion', 'Body Lotion'), ('Body Mist', 'Body Mist'), ('Shampo', 'Shampo'), ('Serums', 'Serums'), ('Conditioner Cream', 'Conditioner Cream'), ('Protein & Creatine', 'Protein & Creatine'), ('Oils', 'Oils')], max_length=50, null=True),
        ),
    ]
