# Generated by Django 3.2.9 on 2021-12-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_postal_code_shippingaddress_telephone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='jov',
        ),
    ]
